# Carregando bibliotecas ----
# source("./R/00.library.R")

# Carregando arquivos ----
# geom_state <- readRDS("./files/shiny_files/geom_state.rds")
data1 <- readRDS("./files/shiny_files/data1.rds")
data2 <- readRDS("./files/shiny_files/data2.rds")
data3 <- readRDS("./files/shiny_files/data3.rds")
data4 <- readRDS("./files/shiny_files/data4.rds")
# data5a <- readRDS("./files/shiny_files/data5a.rds")
# data5b <- readRDS("./files/shiny_files/data5b.rds")
# data5c <- readRDS("./files/shiny_files/data5c.rds")
# data5d <- readRDS("./files/shiny_files/data5d.rds")
# data5e <- readRDS("./files/shiny_files/data5e.rds")
# data5f <- readRDS("./files/shiny_files/data5f.rds")
# # data6 <- readRDS("./files/shiny_files/data6.rds")
# 
# map_city <- "./files/json_files/geojs-100-mun.json"

# worldgeojson <- get_data_from_map(download_map_data("https://code.highcharts.com/mapdata/custom/world.geo.json"))

g_111a <- readRDS("./files/shiny_files/g_111a.rds")
g_111b <- readRDS("./files/shiny_files/g_111b.rds")
g_121 <- readRDS("./files/shiny_files/g_121.rds")
g_211 <- readRDS("./files/shiny_files/g_211.rds")
g_212 <- readRDS("./files/shiny_files/g_212.rds")
g_311 <- readRDS("./files/shiny_files/g_311.rds")
g_312 <- readRDS("./files/shiny_files/g_312.rds")
g_411 <- readRDS("./files/shiny_files/g_411.rds")
g_412 <- readRDS("./files/shiny_files/g_412.rds")
g_413 <- readRDS("./files/shiny_files/g_413.rds")
g_512 <- readRDS("./files/shiny_files/g_512.rds")
g_513 <- readRDS("./files/shiny_files/g_513.rds")
g_521 <- readRDS("./files/shiny_files/g_521.rds")
g_522 <- readRDS("./files/shiny_files/g_522.rds")
g_532 <- readRDS("./files/shiny_files/g_532.rds")
g_533 <- readRDS("./files/shiny_files/g_533.rds")
g_541 <- readRDS("./files/shiny_files/g_541.rds")
g_542 <- readRDS("./files/shiny_files/g_542.rds")
g_551 <- readRDS("./files/shiny_files/g_551.rds")
g_552 <- readRDS("./files/shiny_files/g_552.rds")
g_553 <- readRDS("./files/shiny_files/g_553.rds")
g_562 <- readRDS("./files/shiny_files/g_562.rds")
g_563 <- readRDS("./files/shiny_files/g_563.rds")
